### ISSUE TITLE
Decide on a team chat, discussion, organizing place

### ISSUE THREAD

**Issue by koobs** [bsdlabs/community#1]
* IRC
* Discord
* Somewhere else?

**Comment by khbsd** [comment]
I'm preferential to element.io personally, the  mobile app is a little glitchy at times, but it's verrrryyyyy secure.

**Comment by koobs** [comment]
If we're going for security and mobile support, I'm:

 - +0 on Signal or Telegram, already have them installed, OR
 - +1 Discord (have it installed, able to do voice chat too)

**Comment by khbsd** [comment]
Discord's security is pretty minimal- though we really don't have much to secure. If you want, you can grab the element.io app for your phone and play around with it before we make a decision!

**Comment by koobs** [comment]
I'd *reeeeeeeeeeeeeeeeeeeaaaaaaaaalllllllllly* like to avoid another app on mobile / desktop, and I can see some benefits to us having public activity visible by others in the community, encouraging them to get involved.

For this it feels like Discord is a good place. That's my feeling

**Comment by khbsd** [comment]
That's reasonable! Would we just use the existing #community room in the channel?

**Comment by jhfoo** [comment]
Spin up a server in Discord maybe?

+1 on avoiding yet another app/ chat platform (sorry!)

**Comment by khbsd** [comment]
It's no problem, haha😁 maybe something like #bsdlabs or #labs?

**Comment by jhfoo** [comment]
And so BSDLabs is born: https://discord.gg/YhCCp8uN

Join and I'll make everyone admin (if site permits).

**Comment by khbsd** [comment]
@koobs, what do you think about this?

**Comment by koobs** [comment]
> @koobs, what do you think about this? 

Yep I'm cool with a BSDLabs discord for dedicated or skunkworks stuff, but I'd like to be as public with our social/community team comms as possible, and I think FreeBSD Discord #community is perfect for that, particularly because this team is more broadly about community organising for which FreeBSDHelp & BSDLabs is just a part :)

**Comment by khbsd** [comment]
Rad, considering this closed!

**Comment by koobs** [comment]
Did we doc it? If not, re-open :) 

"definition of done"

**Comment by jhfoo** [comment]
Documented.

**Comment by koobs** [comment]
@jhfoo Always reference issues in commits and/or PR's so that comments are auto-added to the right place when those changes are made. Helps people follow after the fact :)

Can you link the commit?

**Comment by koobs** [comment]
Re 

> 
> 
> > @koobs, what do you think about this?
> 
> Yep I'm cool with a BSDLabs discord for dedicated or skunkworks stuff, but I'd like to be as public with our social/community team comms as possible, and I think FreeBSD Discord #community is perfect for that, particularly because this team is more broadly about community organising for which FreeBSDHelp & BSDLabs is just a part :)

We cool to add a note to the "how we work" section mentioning that the FreeBSD Discord #community channel is the primary place for comms?

While FreeBSDHelp is a personal/private/unofficial account coming under the "BSDLabs" banner and as a BSDLabs initial, the purpose and goal is to build an 'official community organizing capability', so it'd be great (and make more sense, at least to me) if our 'community/social' discussions took place in an official place (ie; the FreeBSD Discord server).

Longer term and as the team grows, I see the team being a touchpoint for people as they find their way into the community, not just social comms.

Note, I'm still happy to have the BSDLabs Discord be the place for higher level stuff and other BSDLabs projects and discussions.

**Comment by jhfoo** [comment]
https://github.com/bsdlabs/community/commit/ddf1dc077faa0802ba4c1162391cf0142067d69c

Like this?

**Comment by jhfoo** [comment]
> Longer term and as the team grows, I see the team being a touchpoint for people as they find their way into the community, not just social comms.

I'm going to stop making further changes, mostly because I'm too new to the purpose and scope of this team to make the right decisions. I can see how this can get more confusing with more people onboard each making decisions from their own assumptions.

@koobs as the founder of this community it may be helpful for you to write a draft RFC on the above, that we can poke and massage until we're all on the same page.

**Comment by koobs** [comment]
It's all good, I think with a pr and review process everyone gets a say and we can see what's up before they go in, but don't worry too much, nothing is set in stone. 

Main goals here are:

- we all refine each other's ideas so as to make better informed decisions
- our decision history is published so that the team (now and future) can always reference and learn from "how we did things and got to where we are"

**Comment by koobs** [comment]
But yep I'll do RFC. Let me know what things you have in mind for that so I can make sure that's covered

**Comment by khbsd** [comment]
Does RFC mean Rules For Communication?

**Comment by jhfoo** [comment]
Request for Comments. :)

**Comment by kfv** [comment]
> We cool to add a note to the "how we work" section mentioning that the FreeBSD Discord #community channel is the primary place for comms?
> 
> While FreeBSDHelp is a personal/private/unofficial account coming under the "BSDLabs" banner and as a BSDLabs initial, the purpose and goal is to build an 'official community organizing capability', so it'd be great (and make more sense, at least to me) if our 'community/social' discussions took place in an official place (ie; the FreeBSD Discord server).
>

I agree with koobs. I'd update the "how we work" section shortly.
 
> Note, I'm still happy to have the BSDLabs Discord be the place for higher level stuff and other BSDLabs projects and discussions.

Same here. It makes total sense, indeed.

@koobs: do we need to re-open the issue, or is it indeed considered closed? I think we need to document what we consider the Definition of Done.

**Comment by khbsd** [comment]
I'll just re-open, since clearly there's more to work out here 😁

**Comment by koobs** [comment]
Update doc, commit log referencing this issue (PR and review if you'd like, for habit, but not strictly necessary), then close :)

**Comment by kfv** [comment]
I had already done a commit, but to act on policy, I removed the commit and just opened a pull request. I am not sure it links fine to the issue as it hasn't shown up here yet, though. Let me know if I did it wrong ;-)

**Comment by koobs** [comment]
> I had already done a commit, but to act on policy, I removed the commit and just opened a pull request. I am not sure it links fine to the issue as it hasn't shown up here yet, though. Let me know if I did it wrong ;-)

[How to link GitHub PR's to Issues or other PRs to link and auto-close them](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by kfv** [comment]
Ah, in the pull request's description or in a commit message! Thanks.

**Comment by koobs** [comment]
@kfv Can you create a CHANGES.md and add this decision as a changelog entry, incl date issue was merged/closed, like:

`<iso-8601-datestamp> <#issue-id> Primary communication channel is FreeBSD Discord: #community`

Don't forget to `Closes #1` on the commit so it closes this issue when done :)

**Comment by kfv** [comment]
Sure! Roger that. I'll do it shortly.
