### ISSUE TITLE
Community Role in FreeBSD Discord

### ISSUE THREAD

**Issue by khbsd** [bsdlabs/community#13]
Should we have a separate role for the members of the team in the FreeBSD Discord Channel? Especially since in #1 we decided the #community channel would be the main place for comms.

Edit to say: admin perms wouldn't really even be necessary, just maybe a different color for organization and easy identification.

- [x] Create community role in FreeBSD Discord
- [x] Set role icon: @freebsdhelp avatar for now
- [x] Update onboarding to include adding team member to community discord role

**Comment by koobs** [comment]
I like it

**Comment by kfv** [comment]
Me too.

**Comment by khbsd** [comment]
Rad! I think @koobs is the only one here with perms on that discord channel, so hopefully when he wakes up from a nice long rest he can get to it 😊

**Comment by koobs** [comment]
We need an icon for the @bsdlabs/community team in Discord. Taking ideas

**Comment by koobs** [comment]
* New @community team created with
 * members: @bluedudexoo @kfv @jhfoo @mc1ay

**Comment by khbsd** [comment]
> We need an icon for the @bsdlabs/community team in Discord. Taking ideas

What about the @freebsdhelp account image?

**Comment by mc1ay** [comment]
I agree, I think the @freebsdhelp image would be good

**Comment by koobs** [comment]
I'm fine with that for now:

 - Matches the freebsdhelp account (connection)
 - But feels a bit too 'helpdesky' for the long term 'community team'

**Comment by koobs** [comment]
Thanks for feedback folks
