### ISSUE TITLE
Create community team landing page for twitter bio / links

### ISSUE THREAD

**Issue by khbsd** [bsdlabs/community#18]
Find the best course of action:

1) make the readme the de-facto landing page, including:
- team overview
- call to action (will ask around for what specifically this could be)

2) create a separate .md specifically for twitter, containing the points above.

**Comment by khbsd** [comment]
Not opening a new issue since this is pretty related, but-
@kfv @koobs can you guys fill out an **About** and **Skills** section in the team.md? I'll use that info to make little intros for everyone. @mitchellclay-asu if you could add a **Skills** section for your entry that'd help too. :)

**Comment by khbsd** [comment]
Updating plans here: 
## README.md as a landing page
### Pros:
- Potentially more visible
- Would make the README.md be more of a homepage, which works with how Github displays info
- Simpler than another file, already has links to most other pages

### Cons:
- README.md may become more complex/longer than is necessary

## Separate CALLTOACTION.md/LANDINGPAGE.md
### Pros:
- More modular
- Avoid overburdening README.md

### Cons:
- Repo would have more overlapping info on multiple pages that would need to be kept consistent
- Might be confusing to have a LANDINGPAGE.md and a README.md

Let me know what you guys think/add pros and cons to this!

**Comment by koobs** [comment]
Yeh, broadly I think community/README.md is the best current place, given the default visibility, its one step less to find the call to action

**Comment by mc1ay** [comment]
Personally, I don’t feel like having a long readme.md is an issue. I do think having a separate landing page is just cumbersome.

**Comment by khbsd** [comment]
Okay: I'll get to work on this!
