### ISSUE TITLE
Document Twitter env setup and add to docs

### ISSUE THREAD

**Issue by koobs** [bsdlabs/community#2]
Document the steps you go through to setup your 'team twitter' environment (for your OS), and document it in a new section in freebsd.md for 'Getting Setup'

**Comment by khbsd** [comment]
I figured it'd be better to have a "Walkthroughs" section in the Onboarding.md- let me know if you think I should move it. :)

**Comment by jhfoo** [comment]
Just do it. :)

**Comment by khbsd** [comment]
Lol, it's been done for a couple hours

**Comment by koobs** [comment]
We should bias toward action, but for anything substantial and as a default, we should issue, pull request and review everything

I'll be populating and seeking feedback on playbook items later this week

**Comment by koobs** [comment]
And thanks for adding those notes, super awesome!

**Comment by khbsd** [comment]
No problem, closing this one 😊
