### ISSUE TITLE
Condensing and Restructuring

### ISSUE THREAD

**Issue by khbsd** [bsdlabs/community#22]
While working on #18, I realized we have some redundancies in guidelines.md and playbook.md- to me, it seems like playbook.md could be a subsection in guidelines.md. How do we feel about this?

**Comment by koobs** [comment]
Distinction between the two:

- guidelines is for @freebsdhelp / social guidelines specifically
- playbook is for internal team operations, process, etc.

**Comment by khbsd** [comment]
I guess my question was, why not have a general `guidelines.md` and then have a "front of house" section and a "back of house" section? They're both technically internal, since the social media guidelines are primarily for team members too.

**Comment by koobs** [comment]
Note: Originally guidelines.md was called freebsdhelp.md

Playbook is also broader, more operational than guidelines (for social media only).

It might help to see the big picture:

bsdlabs
- playbook
- community (team/function)
  - guidelines (for social comms, currently only freebsdhelp. how to do "social" good)
  - playbook (community specific. "how we do "team" things internally, processes, expectations, etc)
- development (team/function)
  -  playbook (development specific)
- marketing (team function)
  -  playbook (marketing specific)

**Comment by khbsd** [comment]
Mmm, okay- this does help. I'll close this!
