### ISSUE TITLE
Implement CHANGELOG.md

### ISSUE THREAD

**Issue by mc1ay** [bsdlabs/community#23]
I like the points made here: [https://keepachangelog.com/en/1.0.0/](https://keepachangelog.com/en/1.0.0/)
We could aim for monthly updates instead of "versions" and we could probably stick to "added", "changed", and "removed" categories.

**Comment by khbsd** [comment]
Since I've already got a WIP branch set up, should I install this on that branch?

**Comment by mc1ay** [comment]
I totally missed that we already had that. I'll close this. Thanks!
