### ISSUE TITLE
Weekly Twitter segment storage

### ISSUE THREAD

**Issue by khbsd** [bsdlabs/community#26]
So- for the weekly segments I write for twitter, I'd like to upload them at the end of each month for people to access and read without scrolling all the way down in our feed. Should I:

### Pros:
- separate from main `community` repo
- slightly more organized

### Cons:
- Might be harder to find if someone came here from the twitter bio
- Feels a little fragmented, personally

### Pros:
- Easy to find
- seems to make sense categorically

### Cons:
- Don't want to make a habit of pushing lots of stuff into the `community` repo
- Would require some extra folders to lay groundwork for other twitter segments

Any suggestions/comments/concerns? :)

**Comment by mc1ay** [comment]
What about doing it as a submodule? That would link it in the repo, but still give you separation.

**Comment by koobs** [comment]
This feels like a 'content creation' thing, which was going to be included in the longer term roadmap for the freebsd community/communications(/content) team.

If that is in line with you the motivations for this question, then im +1 on a `content` repository, that we can later (or now) otherwise link to, or publish in various other ways,

**Comment by khbsd** [comment]
Okay, I've reached a decision- I created a new `content` repo, and I've got a private one on my profile that I'll edit. At the end of every month I'll `--mirror` push to this one so it's up-to-date with the previous segments, but no one can cheat and see the future ones. :)

**Comment by koobs** [comment]
@bluedudexoo Can you doc (changelog) this decision please, thanks!

**Comment by khbsd** [comment]
Done!
