### ISSUE TITLE
Should we always tag tweets (^XX) or not?

### ISSUE THREAD

**Issue by koobs** [bsdlabs/community#3]
Currently the playbook (freebsdhelp.md) has a "DO" item:

    DO tag tweets with a ^XX suffix, where XX are your initials or a similar unique tag

The original rationale for this was so the team could track and see who tweeted what.

Someone [tweeted](https://twitter.com/KatriCameron/status/1456009436976271364) `Y'all should sign your tweets so we know who sends them`, after a few untagged tweets, so it raises the question again (as its obviously important enough for someone to mention), to discuss and decide officially as a team, though there's no rush.

Here are some Pros/Cons I can think of for starters:

## Pros

 - Each team member gets credit
 - We all know who did what
 - We can search for our prior tweets by tag

## Cons

 - Takes up extra space
 - Dilutes the “one personality” brand
 - No real extra value

**Comment by khbsd** [comment]
I'm basically in agreement with the pros/cons here. I think we should try it out with everyone and see how it feels.

**Comment by khbsd** [comment]
@jhfoo @kfv thoughts? :)

**Comment by khbsd** [comment]
Oh, hey! Why don't we post a poll on the Twitter account?

**Comment by jhfoo** [comment]
As a volunteer I'm less interested in personal credit attribution than the success of the team. In my mind our audience sees us as a collective, or even more broadly as 'FreeBSD people'. Honestly if the team failed its goals miserably while I am a rock star in the twitter-verse I will not be inclined to remain.

The team being small makes it super transparent who's really doing all the heavy lifting. I would say let's spend more oxygen on what's good for our mission and for our customers.

/takes off Product hat.

**Comment by kfv** [comment]
Sorry for my late response, everyone. I agree with jhfoo in that the credit for the whole team is much more valuable. It is de facto what per se brings us personal credits as well. In addition, working with a single identity makes our team more flexible - especially in cases that more than one head is required to handle or take over a thread. It'd also be easier for others to follow discussions.

But on the other hand, indeed, we lose track of who's done what, and well, things might go a bit difficult in some rare situations that conflicts arise - which I hope we can withstand and gradually learn how to manage in time.

So I would personally vote against using tags.

**Comment by koobs** [comment]
I like something about the poll idea, but I also love a self directed team that defines who it is and what they care about.

With that and @jhfoo's lovely missive (and the follow up 👍's) I think we're good not to tag tweets.

We can always reeval as we go.

Thanks for the insight and feedback guys, really awesome

Let's 

- update the doc removing that DO
- in the same PR, add a CHANGES.md documenting the decision and summary of main rationale (team over individuals) with a #ref to this issue.

🥳
