### ISSUE TITLE
Merge freebsdhelp.md and guidelines.md into one file

### ISSUE THREAD

**Issue by kfv** [bsdlabs/community#7]
There's a large number of duplicate lines in the name files. We could either merge them into one or revise what they discuss.

- [x] guidelines.md contains all updated content from freebsdhelp.md
- [x] all duplicated information removed from freebsdhelp.md

**Comment by koobs** [comment]
I'll take care of this, as I created the mess (updating freebsdhelp.md at the same time @jhfoo was splitting out the content)

Thanks for creating the issue

**Comment by koobs** [comment]
freebsdhelp.md now only contains the introduction for **that specific** bsdlabs community team 'initiative'

This has left a gap in the main readme.md Introduction, which was freebsdhelp specific, but needs to be a more broad introduction to the bsdlabs **community organizing and communication**, of which freebsdhelp was just the first
practical thing to evolve.

I'll create an issue for this
