### ISSUE TITLE
Mitchell Clay joins the team and is onboarded

### ISSUE THREAD

**Issue by koobs** [bsdlabs/community#8]
- [x] Add to organization
- [x] Add to @FreeBSDHelp Twitter Team
- [x] Mitchell: Onboarding steps done

**Comment by koobs** [comment]
Over to you @mitchellclay-asu!

**Comment by koobs** [comment]
@mitchellclay-asu Do you need help finishing up any of the the onboarding steps, or are you done?

**Comment by mc1ay** [comment]
Everything should be complete now.

**Comment by koobs** [comment]
👍 nice work mate!
